export enum ACTION_MAPPER {
    RENAMED = "renamed",
    CREATED = "created",
    ARCHIVED = "archived",
    DISMISSED = "dismissed",
    CHANGED_THE_DESCRIPTION = "changed the card description",
    REMOVED = "removed",
    INVITE = "invite",
    ADMINADD = "adminAdd",
    ADMINREMOVE = "adminRemove",
    CARDJOINED = 'joined the card.',
    CARDDECLINED = 'cardDecline',
    NOTECREATED = 'created',
    NOTERENAMED = 'renamed',
    NOTEDELETED = 'deleted',
    FILEUPLOAD = 'uploaded',
    FILERENAMED = 'renamed $name to',
    FILEDELETED = 'deleted',
    FILEBULKUPLOAD = 'uploaded $count files',
    TASKCRETED = 'created',
    TASKRENAMED = 'renamed',
    TASKCOMPLETED = 'complete',
    TASKDELETED = 'deleted',
    TASKINCOMPLETE = 'marked',
    TASKREQUESTUPDATE = 'requests updates for',
    TASKSTARTED = 'started'
}

export const ACTION_TITLE_MAPPER = {
    "renamed": "{name,newName}",
    "created": "this card",
    "archived": "this card",
    "dismissed": "this card",
    "changed the card description": "{name,newName}",
    "removed": "{userId}",
    "invite": "{userId}",
    "adminAdd": "{userId}",
    "adminRemove": "{userId}",
    "joined the card.": "",
    "cardDecline": "",
    "note_created": "{notetitle}",
    "note_renamed": "{old,new}",
    "note_deleted": "{notetitle}",
    "file_uploaded": "$count files",
    "file_renamed": "{name,newName}",
    "file_deleted": "",
    "file_bulk_upload": "$count files",
    "task_created": "$projectName",
    "task_renamed": "$name, $projectName",
    "task_completed": "$projectName",
    "task_deleted": "$projectName",
    "task_requpdate": "$projectName",
    "task_started": "$projectName",
    "task_incomplete": "$projectName"
}