name: Preview for Prod to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependency
        run: npm install

      - name: build Prod
        run: npm run build_prod
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKKEY_PROD }}'
          projectId: taskkey-prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels